myweb/imdb/urls.py
from django.urls import path, include
from . import views

app_name = 'imdb'
urlpatterns = [
    # Index
    path('', views.index, name='index'),
    
    # Authentication URLS
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('signup/success/', views.signup_success, name='signup_success'),

    # Movie URLS
    path('movies/', views.movies, name='movies'),
    path('movies/add/', views.add_movie, name='addmovie'),
    path('movies/detail/<int:pk>/', views.movie_detail, name="moviedetail"),
    path('movies/detail/<int:pk>/update/', views.update_movie, name="updatemovie"),
    path('movies/detail/<int:pk>/delete/', views.delete_movie, name="deletemovie"),


    # Actor URLS
    path('actors/', views.actors, name='actors'),
    path('actors/add/', views.add_actor, name='addactor'),
    path('actors/detail/<int:pk>/', views.actor_detail, name="actordetail"),
    path('actors/detail/<int:pk>/update/', views.update_actor, name="updateactor"),
    path('actors/detail/<int:pk>/delete/', views.delete_actor, name="deleteactor"),

    # Award URLS
    path('awards/', views.awards, name='awards'),
    path('awards/add/', views.add_award, name='addaward'),
    path('awards/detail/<int:pk>/', views.award_detail, name="awarddetail"),
    path('awards/detail/<int:pk>/update/', views.update_award, name="updateaward"),
    path('awards/detail/<int:pk>/assign', views.assign_award, name='assignaward'),
    path('awards/detail/<int:pk>/delete/', views.delete_award, name="deleteaward"),

    # User URLS
    path('users/', views.users, name='users'),

    # Comment URLS
    path('comment/<int:pk>', views.movie_detail, name="addcomment"),
    path('comment/<int:pk>/', views.comment_update, name='comment-update'),
    path('comment/<int:pk>/delete/', views.comment_delete, name='comment-delete'),
]

myweb/myweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('imdb/', include("imdb.urls")),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myweb/imdb/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.hashers import make_password, check_password
from imdb.models import Login, Movie, Actor, Award, Comment
from django.contrib.auth.models import User
from datetime import datetime


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, label='Username')
    password = forms.CharField(max_length=100, label='Password',
                               widget=forms.PasswordInput)

    class Meta:
        fields = ('username', 'password')

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        username_list = list(User.objects.values_list('username', flat=True))
        if username not in username_list:
            raise forms.ValidationError(
                'Username not found, please create an account.'
            )
        user_obj = User.objects.get(username=username)
        if not check_password(password, user_obj.password):
            raise forms.ValidationError(
                'Password invalid, please try again.'
            )


class SignupForm(forms.ModelForm):
    password_confirm = forms.CharField(widget=forms.PasswordInput,
                                       help_text="Re-enter your password.")

    class Meta:
        model = User
        fields = ('username', 'password', 'password_confirm',)

        labels = {
            'username': _('Username'),
            # 'email_address': _('Email address *'),
            'password': _('Password'),
            'password_confirm': _('Password confirmation'),
        }
        widgets = {
            'password': forms.PasswordInput,
            # 'password_confirm': forms.PasswordInput,
            # 'email_address': forms.EmailInput,
        }
        help_texts = {
            'username': _('Username may only contain alphanumeric characters\
                          or single hyphens,and cannot begin or end with a hy\
                          phen.'),
            'password': _("Make sure it's more than 15 characters OR at least\
                          8 characters including a number and a lowercase let\
                          ter."),
            # 'password_confirm': _("Re-enter your password.",)
        }
        error_messages = {
            'username': {
                'max_length': _("This username is too long."),
            },
        }

    def clean(self):
        cleaned_data = super(SignupForm, self).clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if not check_password(password_confirm, password):
            raise forms.ValidationError(
                'Password and confirmation password does not match.'
            )
        username_list = list(User.objects.values_list('username', flat=True))
        username = cleaned_data.get('username')
        if username in username_list:
            raise forms.ValidationError(
                'This name has exist, please choose another name.'
            )

    def clean_password(self):
        encrypt_password = make_password(self.cleaned_data['password'])
        if encrypt_password:
            return encrypt_password
        else:
            raise forms.ValidationError(
                'Password encryption fail, please choose another password'
            )


class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = "__all__"
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your movie name'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Movie description', 'rows': '3',}),
            'release_date': forms.SelectDateWidget(years=range(datetime.today().year, 1800, -1), attrs={'class': 'form-control'}),
            'categories': forms.Select(attrs={'class': 'custom-select d-block w-100',}),
            'actors': forms.CheckboxSelectMultiple,
            'logo': forms.FileInput(attrs={'class': 'custom-file-input',}),
        }


class ActorForm(forms.ModelForm):  
    
    class Meta:
        model = Actor
        fields = "__all__"
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control',}),
            'last_name': forms.TextInput(attrs={'class': 'form-control',}),
            'birthdate': forms.SelectDateWidget(years=range(datetime.today().year, 1800, -1), attrs={'class': 'form-control'}),
            'sex': forms.Select(attrs={'class': 'custom-select d-block w-100',}),
            'nationalities': forms.Select(attrs={'class': 'custom-select d-block w-100',}),
            'alive': forms.CheckboxInput(attrs={'class': 'custom-control-input',}),
        }


class AwardCreateForm(forms.ModelForm):
    
    class Meta:
        model = Award
        fields = ('name', 'kind', )
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control',}),
            'kind': forms.Select(attrs={'class': 'custom-select d-block w-100',}),
        }


class AwardAssignForm(forms.ModelForm):

    class Meta:
        model = Award
        fields = ('movie_kind', 'actor_kind',)
        widgets = {
            'movie_kind': forms.CheckboxSelectMultiple,
            'actor_kind': forms.CheckboxSelectMultiple,
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Add your comment', 'rows': '3',}),
        }


class CommentChangeForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Add your comment', 'rows': '3',}),
        }

myweb/imdb/templates/imdb/award_detail.html
{% extends 'imdb/base.html' %}

{% block award_detail %}
{% load static %}
<link href="{% static "imdb/product.css" %}" rel="stylesheet">

<body>

<div class="pos-f-t">
    <div class="collapse fixed-top" id="navbarToggleExternalContent">
        <div class="bg-dark p-4">
          <h5 class="text-white h4">Welcome to IMDB index page.</h5>
          <span class="text-muted">The largest internet movie database.</span>
        </div>
    </div>
</div>

<nav class="navbar fixed-top navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <a class="btn btn-outline-primary" href="{% url "imdb:index" %}">IMDB</a>
    <a class="nav-link" href="{% url "imdb:movies" %}">Movies</a>
    <a class="nav-link" href="{% url "imdb:actors" %}">Actors</a>
    <a class="nav-link" href="{% url "imdb:awards" %}">Awards</a>

    <form class="form-inline">
        {% if user.is_authenticated %}
        <a class="btn btn-danger" href="{% url "imdb:logout" %}">Log-out</a>
        {% else %}
        <a class="btn btn-primary" href="{% url "imdb:login" %}">Log-in</a>
        <a class="btn btn-link" href="{% url "imdb:signup" %}">Sign-up</a>
        {% endif %}
    </form>
</nav>

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">

  <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#award_edit{{ obj.id }}">Edit</button>
  {% comment %} MODAL FOR AWARD EDIT BUTTON {% endcomment %}
  <div class="modal fade bd-example-modal-lg" id="award_edit{{ obj.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">

        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit form</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <form action="{% url "imdb:updateaward" obj.id %}" method="post">
        {% csrf_token %}

        <div class="modal-body text-left">
          <div class="form-group">

            <div class="mb-3">
            <label>Award Name:</label>
            {{ pre_form.name }}
            </div>

            <div class="mb-3">
            <label>Award Kind:</label>
            {{ pre_form.kind }}
            </div>

          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <input class="btn btn-danger" type="submit" value="Submit">
        </div>

        </form>

      </div>
    </div>
  </div>
  <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#award_assign{{ obj.id }}">Assign</button>
  {% comment %} MODAL FOR AWARD ASSIGN BUTTON {% endcomment %}
  <div class="modal fade bd-example-modal-lg" id="award_assign{{ obj.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">

        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit form</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <form action="{% url "imdb:assignaward" obj.id %}" method="post">
        {% csrf_token %}

        <div class="modal-body text-left">
          <div class="form-group">

            {% if obj.kind == "MOVIE" %}
            <div class="mb-3">
            <label>Award Name:</label>
            {{ assign_form.movie_kind }}
            </div>
            {% else %}
            <div class="mb-3">
            <label>Award Name:</label>
            {{ assign_form.actor_kind }}
            </div>
            {% endif %}

          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <input class="btn btn-danger" type="submit" value="Submit">
        </div>

        </form>

      </div>
    </div>
  </div>

  <img class="center" src="{% static "imdb/images/award.png" %}" alt="">

  <div class="col-md-auto p-lg-10 mx-auto my-5 text-left">
  <hr class="mb-4">
    <h5 class="display-4 font-weight-normal">{{ obj }}</h>
    <p></p>
    <p class="lead font-weight-normal"><span class="badge badge-info">Award Name</span> {{ obj.name }}</p>
    <p class="lead font-weight-normal"><span class="badge badge-info">Award Kind</span> {{ obj.kind }}</p>
    <p class="lead font-weight-normal"><span class="badge badge-info">Assign to</span></p>
    <p class="lead font-weight-normal">
    {% if obj.kind == "MOVIE" and obj.movie_kind.all %}
    {% for movie in obj.movie_kind.all %}
    <a href="{% url "imdb:moviedetail" movie.id %}" class="lead font-weight-normal">{{ movie }}</a>
    ,
    {% endfor %}
    </p>

    {% elif obj.kind == "ACTOR" and obj.actor_kind.all %}
    <p class="lead font-weight-normal">
    {% for actor in obj.actor_kind.all %}
    <a href="{% url "imdb:actordetail" actor.id %}" class="lead font-weight-normal">{{ actor }}</a>
    ,
    {% endfor %}
    </p>
    {% endif %}
    <p class="lead font-weight-normal"><span class="badge badge-info">Award assign time</span> {{ obj.date_assign }}</p>
  </div>

</div>

<div class="center">

  <div class="card">

    <div class="card-body">

    {% for comment in load_comments %}

    <div class="card">

      <div class="card-body">
        {% comment %} MODAL {% endcomment %}
        {% if user.id == comment.user.id or user.is_staff or user.is_superuser %}
          {% comment %} DELETE BUTTON {% endcomment %}
          <button type="button" class="btn btn-danger float-right" data-toggle="modal" data-target="#delete{{ comment.id }}">Delete</button>
          {% comment %} MODAL FOR DELETE BUTTON {% endcomment %}
          <div class="modal fade" id="delete{{ comment.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Delete comment</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

                <form action="{% url "imdb:comment-delete" comment.id %}" method="post">
                {% csrf_token %}

                <div class="modal-body">
                  <div class="form-group">
                    <div class='card'><div class='card-body'><p>{{ comment.content }}</p></div></div>
                  </div>
                  <div class="form-group">
                    <label for="message-text" class="col-form-label">Are you sure to delete this comment?</label>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <input class="btn btn-danger" type="submit" value="Submit">
                </div>
                </form>
              </div>
            </div>
          </div>

          <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#edit{{ comment.id }}">Edit</button>
          {% comment %} MODAL FOR EDIT BUTTON {% endcomment %}
          <div class="modal fade" id="edit{{ comment.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Edit comment</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

                <form action="{% url "imdb:comment-update" comment.id %}" method="post">
                {% csrf_token %}

                <div class="modal-body">
                  <div class="form-group">
                    <label for="recipient-name" class="col-form-label">Current:</label>
                    <div class='card'><div class='card-body'><p>{{ comment.content }}</p></div></div>
                  </div>
                  <div class="form-group">
                    <label for="message-text" class="col-form-label">Change to:</label>
                    <textarea class="form-control" id="message-text" name="comment_update"></textarea>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <input class="btn btn-primary" type="submit" value="Save changes">
                </div>
                </form>
              </div>
            </div>
          </div>
        {% endif %}
        {% comment %} END OF MODAL SECTION {% endcomment %}

        {% comment %} LOAD COMMENTS {% endcomment %}
        <h5 class="card-title">{{ comment.user }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
        {{ comment.created_time }}
          {% if comment.last_edit %}
          (edited: {{ comment.last_edit }})
          {% endif %}
        </h6>
        <p class="card-text">{{ comment.content }}</p>

      </div>

    </div>

    <hr class='mb4'>

    {% endfor %}

    </div>

  </div>

  </br>

  {% comment %} ADD COMMENT FORM {% endcomment %}
  <form action="{% url "imdb:addcomment" obj.id %}" method="post">
    {% csrf_token %}

    <input type="hidden" name="kind" value="Award">

    {{ cmt_form.content }}

    </br>

    <input class="btn btn-primary float-right" type="submit" value="Add comment">

    </br>
    </br>

  </form>

</div>

</body>
{% endblock %}

myweb/imdb/templates/imdb/movie_detail.html
{% extends 'imdb/base.html' %}

{% block movie_detail %}
{% load static %}
<link href="{% static "imdb/product.css" %}" rel="stylesheet">
<body>

<div class="pos-f-t">
    <div class="collapse fixed-top" id="navbarToggleExternalContent">
        <div class="bg-dark p-4">
          <h5 class="text-white h4">Welcome to IMDB index page.</h5>
          <span class="text-muted">The largest internet movie database.</span>
        </div>
    </div>
</div>

{% comment %} MODAL {% endcomment %}


{% comment %} END MODAL {% endcomment %}

<nav class="navbar fixed-top navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <a class="btn btn-outline-primary" href="{% url "imdb:index" %}">IMDB</a>
    <a class="nav-link" href="{% url "imdb:movies" %}">Movies</a>
    <a class="nav-link" href="{% url "imdb:actors" %}">Actors</a>
    <a class="nav-link" href="{% url "imdb:awards" %}">Awards</a>

    <form class="form-inline">
        {% if user.is_authenticated %}
        <a class="btn btn-danger" href="{% url "imdb:logout" %}">Log-out</a>
        {% else %}
        <a class="btn btn-primary" href="{% url "imdb:login" %}">Log-in</a>
        <a class="btn btn-link" href="{% url "imdb:signup" %}">Sign-up</a>
        {% endif %}
    </form>
</nav>

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">

  <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#movie_edit{{ obj.id }}">Edit</button>
  {% comment %} MODAL FOR MOVIE EDIT BUTTON {% endcomment %}
  <div class="modal fade bd-example-modal-lg" id="movie_edit{{ obj.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">

        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit form</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <form action="{% url "imdb:updatemovie" obj.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="modal-body text-left">
          <div class="form-group">


            <div class="mb-3">
              <label for="id_title">Title:</label>
              {{ pre_form.title }}
            </div>

            <div class="form-group green-border-focus">
              <label for="id_description">Description:</label>
              {{ pre_form.description }}
            </div>

            <div class="mb-3">
              <label for="id_release_date_month">Release date:</label>
              <div class="input-group">
              {{ pre_form.release_date }}
              </div>
            </div>

            {% if user.is_superuser %}
            <div class="mb-3">
              <label for="id_categories">Category:</label>
              {{ pre_form.categories }}
            </div>
            {% endif %}

            <label>Actors:</label>
            {{ pre_form.actors }}

            <div class="custom-file">
              {{ pre_form.logo }}
              <label class="custom-file-label" for="id_logo">Choose file...</label>
            </div>

          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <input class="btn btn-danger" type="submit" value="Submit">
        </div>

        </form>
      </div>
    </div>
  </div>

  <img class="center" src="/media/{{ obj.logo }}" alt="">

  <div class="col-md-auto p-lg-10 mx-auto my-5 text-left">

    <hr class="mb-4">
    <h5 class="display-4 font-weight-normal">{{ obj.title }}</h>
    <hr class="mb-4">

    <p></p>

    <p class="lead font-weight-normal"><span class="badge badge-info">Genre</span> {{ obj.categories.capitalize }}</p>
    <p class="lead font-weight-normal"><span class="badge badge-info">Actors</span></p>

    <p class="lead font-weight-normal">
    {% for actor in obj.actors.all %}
    <a href="{% url "imdb:actordetail" actor.id %}" class="lead font-weight-normal">{{ actor }}</a>
    ,
    {% endfor %}
    </p>

    <p class="lead font-weight-normal"><span class="badge badge-info">Release date</span></p>
    <p class="lead font-weight-normal">{{ obj.release_date }}</p>
    <p class="lead font-weight-normal"><span class="badge badge-info">Description</span></p>
    <p class="lead font-weight-normal">{{ obj.description }}</p>
    <p class="lead font-weight-normal"><span class="badge badge-info">Award</span></p>
    {% for award in obj.award_set.all %}
    <p class="lead font-weight-normal"><a href="{% url "imdb:awarddetail" award.id %}">{{ award }}</a></p>
    {% endfor %}

  </div>

</div>

<div class="center">

  <div class="card">

    <div class="card-body">

    {% for comment in load_comments %}

    <div class="card">

      <div class="card-body">
        {% comment %} MODAL {% endcomment %}
        {% if user.id == comment.user.id or user.is_staff or user.is_superuser %}
          {% comment %} DELETE BUTTON {% endcomment %}
          <button type="button" class="btn btn-danger float-right" data-toggle="modal" data-target="#delete{{ comment.id }}">Delete</button>
          {% comment %} MODAL FOR DELETE BUTTON {% endcomment %}
          <div class="modal fade" id="delete{{ comment.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Delete comment</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

                <form action="{% url "imdb:comment-delete" comment.id %}" method="post">
                {% csrf_token %}

                <div class="modal-body">
                  <div class="form-group">
                    <div class='card'><div class='card-body'><p>{{ comment.content }}</p></div></div>
                  </div>
                  <div class="form-group">
                    <label for="message-text" class="col-form-label">Are you sure to delete this comment?</label>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <input class="btn btn-danger" type="submit" value="Submit">
                </div>
                </form>
              </div>
            </div>
          </div>

          <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#edit{{ comment.id }}">Edit</button>
          {% comment %} MODAL FOR EDIT BUTTON {% endcomment %}
          <div class="modal fade" id="edit{{ comment.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Edit comment</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

                <form action="{% url "imdb:comment-update" comment.id %}" method="post">
                {% csrf_token %}

                <div class="modal-body">
                  <div class="form-group">
                    <label for="recipient-name" class="col-form-label">Current:</label>
                    <div class='card'><div class='card-body'><p>{{ comment.content }}</p></div></div>
                  </div>
                  <div class="form-group">
                    <label for="message-text" class="col-form-label">Change to:</label>
                    <textarea class="form-control" id="message-text" name="comment_update"></textarea>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <input class="btn btn-primary" type="submit" value="Save changes">
                </div>
                </form>
              </div>
            </div>
          </div>
        {% endif %}
        {% comment %} END OF MODAL SECTION {% endcomment %}

        {% comment %} LOAD COMMENTS {% endcomment %}
        <h5 class="card-title">{{ comment.user }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
        {{ comment.created_time }}
          {% if comment.last_edit %}
          (edited: {{ comment.last_edit }})
          {% endif %}
        </h6>
        <p class="card-text">{{ comment.content }}</p>

      </div>

    </div>

    <hr class='mb4'>

    {% endfor %}

    </div>

  </div>

  </br>

  {% comment %} ADD COMMENT FORM {% endcomment %}
  <form action="{% url "imdb:addcomment" obj.id %}" method="post">
    {% csrf_token %}

    <input type="hidden" name="kind" value="Movie">

    {{ cmt_form.content }}

    </br>

    <input class="btn btn-primary float-right" type="submit" value="Add comment">

    </br>
    </br>

  </form>

</div>


</body>
{% endblock %}

myweb/imdb/templates/imdb/signup.html
{% extends 'imdb/base.html' %}

{% block signup %}
<div class="container">
</br>
<h1>Create your account:</h1>
</br>
<form action="{% url "imdb:signup" %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group row">
        <label for="id_username" class="col-sm-2 col-form-label">Username:</label>
        <div class="col-sm-7">
            <input type="text" class="form-control" id="id_username" name="username" placeholder="Username">
        </div>
    </div>

    {{ form.password.errors }}
    <div class="form-group row">
        <label for="id_password" class="col-sm-2 col-form-label">Password:</label>
        <div class="col-sm-7">
            <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
        </div>
    </div>

    {{ form.password_confirm.errors }}
    <div class="form-group row">
        <label for="id_password_confirm" class="col-sm-2 col-form-label">Password confirmation:</label>
        <div class="col-sm-7">
            <input type="password" class="form-control" id="id_password_confirm" name="password_confirm" placeholder="Password confirmation">
        </div>
    </div>
    </br>
    <input type="submit" class="btn btn-success" value="Signup">
    <a class="btn btn-link" href="{% url "imdb:index" %}">Homepage</a>
</form>
</div>

{% endblock %}

myweb/imdb/templates/imdb/signup_success.html
{% extends 'imdb/base.html' %}

{% block signup_success %}
</br>
<div class='container'>
    <h1>Sign-up success.</h1>
    </br>
    <a href={% url "imdb:login" %} class='btn btn-primary'>Log-in</a>
</div>
{% endblock %}